# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: GiulianoBellini.Sniffnet
PackageVersion: 1.3.2
PackageLocale: en-US
Publisher: Giuliano Bellini
PublisherUrl: https://github.com/GyulyVGC
PublisherSupportUrl: https://github.com/GyulyVGC/sniffnet/issues
PackageName: Sniffnet
PackageUrl: https://github.com/GyulyVGC/sniffnet
License: Apache-2.0
ShortDescription: "Comfortably monitor your Internet traffic \U0001F575️‍♂️"
Tags:
- application
- gui
- iced
- linux
- macos
- network
- network-analysis
- network-monitoring
- networking
- packet-analyser
- packet-capture
- packet-sniffer
- pcap
- rust
- rust-crate
- security
ReleaseNotesUrl: https://github.com/GyulyVGC/sniffnet/releases/tag/v1.3.2
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/GyulyVGC/sniffnet/wiki
ManifestType: defaultLocale
ManifestVersion: 1.9.0
