# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: EDRLab.Thorium
PackageVersion: 3.1.0
PackageLocale: en-US
Publisher: EDRLab
PublisherUrl: https://github.com/edrlab/thorium-reader
PublisherSupportUrl: https://github.com/edrlab/thorium-reader/issues
Author: EDRLab
PackageName: Thorium
PackageUrl: https://github.com/edrlab/thorium-reader
License: BSD-3-Clause
LicenseUrl: https://github.com/edrlab/thorium-reader/blob/HEAD/LICENSE
Copyright: Copyright (c) 2022 EDRLab
CopyrightUrl: https://raw.githubusercontent.com/edrlab/thorium-reader/develop/LICENSE
ShortDescription: A cross platform desktop reading app, based on the Readium Desktop toolkit
Tags:
- electron
- epub
- epub-reader
- epub3
- lcp
- opds
- opds-feed
- react
- reader
- redux
- typescript
ReleaseNotesUrl: https://github.com/edrlab/thorium-reader/releases/tag/v3.1.0
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/edrlab/thorium-reader/wiki
ManifestType: defaultLocale
ManifestVersion: 1.9.0
